---
title: "Nielsen Movers Analysis"
author: "Daniel O'Leary"
date: "3/14/2021"
output:
  github_document:
    toc: true
    toc_depth: 5
---

```{r, include = FALSE}
if (!require("pacman")) install.packages("pacman")

pacman::p_load(
  tidyverse, 
  haven,
  lme4,
  lm.beta,
  sjPlot,
  stargazer
)
```

```{r, include = FALSE}
sinfo <- data.frame(Sys.info())
machine <- sinfo$Sys.info..[4]

machine_path <- 
  ifelse(
    machine %in% c("sussman-rp-mbpro.local", "sussman-rp-mbpro.lan"), 
    "/Users/djolear/Google Drive/", 
    "G:/My Drive/"
  )


```


# Analysis

## Zipcode moves

### 1 year

```{r}
 lm_z1 <-
    lmer(
      scale(yes_scale_t2) ~
        scale(yes_scale_t1) +
        
        scale(I(median_income_county_t2 - median_income_county_t1)) +
        median_income_county_scale_t1 +
        
        scale(I(physicians_scale_t2 - physicians_scale_t1)) +
        physicians_scale_t1 +
        
        # scale(I(dentists_t2 - dentists_t1)) +
        # scale(dentists_t1) +
        # 
        # scale(I(therapists_t2 - therapists_t1)) +
        # scale(therapists_t1) +
        
        scale(I(median_monthly_housing_cost_county_t2 - median_monthly_housing_cost_county_t1)) +
        median_monthly_housing_cost_county_scale_t1 +
        
        scale(I(income_t2 - income_t1)) +
        income_scale_t1 +
        
        scale(I(Male_Head_Education_t2 - Male_Head_Education_t1)) +
        Male_Head_Education_scale_t1 +
        
        scale(I(Female_Head_Education_t2 - Female_Head_Education_t1)) +
        Female_Head_Education_scale_t1 +
        
        scale(I(Male_Head_Age_t2 - Male_Head_Age_t1)) +
        Male_Head_Age_scale_t1 +
        
        scale(I(Female_Head_Age_t2 - Female_Head_Age_t1)) +
        Female_Head_Age_scale_t1 +
        
        scale(I(total_pop_county_t2 - total_pop_county_t1)) +
        total_pop_county_scale_t1 +
        
        scale(I(land_area_2010_t2 - land_area_2010_t1)) +
        land_area_2010_scale_t1 +
        
        scale(I(Household_Size_t2 - Household_Size_t1)) +
        Household_Size_scale_t1 +
        
        Race_t1 +
        
        Male_Head_Employment_t1 +
        Female_Head_Employment_t1 +
        Marital_Status_t1 +
        
        Male_Head_Employment_t2 +
        Female_Head_Employment_t2 +
        Marital_Status_t2 +
        
        year_t1 +
        
        (1 + scale(I(median_income_county_t2 - median_income_county_t1))|fips_code_t2) +
        (1|fips_code_t1) +
        (1|household_code) +
        (1|quarter),
      data =
        zip_movers_1yr_data
    )

summary(lm_z1)
```

### 2 years

```{r}
 lm_z2 <-
    lmer(
      scale(yes_scale_t2) ~
        scale(yes_scale_t1) +
        
        scale(I(median_income_county_t2 - median_income_county_t1)) +
        median_income_county_scale_t1 +
        
        scale(I(physicians_scale_t2 - physicians_scale_t1)) +
        physicians_scale_t1 +
        
        # scale(I(dentists_t2 - dentists_t1)) +
        # scale(dentists_t1) +
        # 
        # scale(I(therapists_t2 - therapists_t1)) +
        # scale(therapists_t1) +
        
        scale(I(median_monthly_housing_cost_county_t2 - median_monthly_housing_cost_county_t1)) +
        median_monthly_housing_cost_county_scale_t1 +
        
        scale(I(income_t2 - income_t1)) +
        income_scale_t1 +
        
        scale(I(Male_Head_Education_t2 - Male_Head_Education_t1)) +
        Male_Head_Education_scale_t1 +
        
        scale(I(Female_Head_Education_t2 - Female_Head_Education_t1)) +
        Female_Head_Education_scale_t1 +
        
        scale(I(Male_Head_Age_t2 - Male_Head_Age_t1)) +
        Male_Head_Age_scale_t1 +
        
        scale(I(Female_Head_Age_t2 - Female_Head_Age_t1)) +
        Female_Head_Age_scale_t1 +
        
        scale(I(total_pop_county_t2 - total_pop_county_t1)) +
        total_pop_county_scale_t1 +
        
        scale(I(land_area_2010_t2 - land_area_2010_t1)) +
        land_area_2010_scale_t1 +
        
        scale(I(Household_Size_t2 - Household_Size_t1)) +
        Household_Size_scale_t1 +
        
        Race_t1 +
        
        Male_Head_Employment_t1 +
        Female_Head_Employment_t1 +
        Marital_Status_t1 +
        
        Male_Head_Employment_t2 +
        Female_Head_Employment_t2 +
        Marital_Status_t2 +
        
        year_t1 +
        
        (1 + scale(I(median_income_county_t2 - median_income_county_t1))|fips_code_t2) +
        (1|fips_code_t1) +
        (1|household_code) +
        (1|quarter),
      data =
        zip_movers_2yr_data
    )

summary(lm_z2)
```


## County moves

### 1 year

```{r}
 lm_f1 <-
    lmer(
      scale(yes_scale_t2) ~
        scale(yes_scale_t1) +
        
        scale(I(median_income_county_t2 - median_income_county_t1)) +
        median_income_county_scale_t1 +
        
        scale(I(physicians_scale_t2 - physicians_scale_t1)) +
        physicians_scale_t1 +
        
        # scale(I(dentists_t2 - dentists_t1)) +
        # scale(dentists_t1) +
        # 
        # scale(I(therapists_t2 - therapists_t1)) +
        # scale(therapists_t1) +
        
        scale(I(median_monthly_housing_cost_county_t2 - median_monthly_housing_cost_county_t1)) +
        median_monthly_housing_cost_county_scale_t1 +
        
        scale(I(income_t2 - income_t1)) +
        income_scale_t1 +
        
        scale(I(Male_Head_Education_t2 - Male_Head_Education_t1)) +
        Male_Head_Education_scale_t1 +
        
        scale(I(Female_Head_Education_t2 - Female_Head_Education_t1)) +
        Female_Head_Education_scale_t1 +
        
        scale(I(Male_Head_Age_t2 - Male_Head_Age_t1)) +
        Male_Head_Age_scale_t1 +
        
        scale(I(Female_Head_Age_t2 - Female_Head_Age_t1)) +
        Female_Head_Age_scale_t1 +
        
        scale(I(total_pop_county_t2 - total_pop_county_t1)) +
        total_pop_county_scale_t1 +
        
        scale(I(land_area_2010_t2 - land_area_2010_t1)) +
        land_area_2010_scale_t1 +
        
        scale(I(Household_Size_t2 - Household_Size_t1)) +
        Household_Size_scale_t1 +
        
        Race_t1 +
        
        Male_Head_Employment_t1 +
        Female_Head_Employment_t1 +
        Marital_Status_t1 +
        
        Male_Head_Employment_t2 +
        Female_Head_Employment_t2 +
        Marital_Status_t2 +
        
        year_t1 +
        
        (1 + scale(I(median_income_county_t2 - median_income_county_t1))|fips_code_t2) +
        (1|fips_code_t1) +
        (1|household_code) +
        (1|quarter),
      data =
        fips_movers_1yr_data
    )

summary(lm_f1)
```


### 2 years

```{r}
 lm_f2 <-
    lmer(
      scale(yes_scale_t2) ~
        scale(yes_scale_t1) +
        
        scale(I(median_income_county_t2 - median_income_county_t1)) +
        median_income_county_scale_t1 +
        
        scale(I(physicians_scale_t2 - physicians_scale_t1)) +
        physicians_scale_t1 +
        
        # scale(I(dentists_t2 - dentists_t1)) +
        # scale(dentists_t1) +
        # 
        # scale(I(therapists_t2 - therapists_t1)) +
        # scale(therapists_t1) +
        
        scale(I(median_monthly_housing_cost_county_t2 - median_monthly_housing_cost_county_t1)) +
        median_monthly_housing_cost_county_scale_t1 +
        
        scale(I(income_t2 - income_t1)) +
        income_scale_t1 +
        
        scale(I(Male_Head_Education_t2 - Male_Head_Education_t1)) +
        Male_Head_Education_scale_t1 +
        
        scale(I(Female_Head_Education_t2 - Female_Head_Education_t1)) +
        Female_Head_Education_scale_t1 +
        
        scale(I(Male_Head_Age_t2 - Male_Head_Age_t1)) +
        Male_Head_Age_scale_t1 +
        
        scale(I(Female_Head_Age_t2 - Female_Head_Age_t1)) +
        Female_Head_Age_scale_t1 +
        
        scale(I(total_pop_county_t2 - total_pop_county_t1)) +
        total_pop_county_scale_t1 +
        
        scale(I(land_area_2010_t2 - land_area_2010_t1)) +
        land_area_2010_scale_t1 +
        
        scale(I(Household_Size_t2 - Household_Size_t1)) +
        Household_Size_scale_t1 +
        
        Race_t1 +
        
        Male_Head_Employment_t1 +
        Female_Head_Employment_t1 +
        Marital_Status_t1 +
        
        Male_Head_Employment_t2 +
        Female_Head_Employment_t2 +
        Marital_Status_t2 +
        
        year_t1 +
        
        (1 + scale(I(median_income_county_t2 - median_income_county_t1))|fips_code_t2) +
        (1|fips_code_t1) +
        (1|household_code) +
        (1|quarter),
      data =
        fips_movers_2yr_data
    )

summary(lm_f2)
tidy(lm_f2)
```