---
title: "Nielsen Relative Status Regression Analysis"
author: "Daniel O'Leary"
date: "4/12/2021"
output:
  github_document:
    toc: true
    toc_depth: 5
---

```{r, include = FALSE}
if (!require("pacman")) install.packages("pacman")

pacman::p_load(
  tidyverse, 
  haven,
  lme4,
  lm.beta,
  sjPlot,
  stargazer,
  broom,
  broom.mixed,
  gbm
)
```

```{r}
nielsen_calorie_budget <-
  read_csv("D:/data/nielsen/qfahpd_health_calories_imputed_sc_by_household_quarterly/qh_calories_imputed_sc_by_household_quarterly_wide_secondary_all_years.csv")


nielsen_dollar_budget <-
  read_csv("D:/data/nielsen/qfahpd_health_spend_by_household_quarterly/qh_spend_by_household_quarterly_wide_secondary_all_years.csv")

nielsen_calorie_budget <- nielsen_calorie_budget %>% left_join(nielsen_dollar_budget %>% dplyr::select(household_code, income_demo_ranger_sar_scale, year) %>% distinct())
```


```{r}
lm1 <-
  lm(
    yes_scale ~
      income_demo_ranger_sar_scale +
      income_scale +
      Male_Head_Education_scale +
      Female_Head_Education_scale +
      Male_Head_Age_scale + 
      # Female_Head_Age_scale +
      # as.factor(Male_Head_Employment) +
      # as.factor(Female_Head_Employment) +
      median_home_value_county_scale +
      land_area_2010_scale +
      total_pop_county_scale +
      Race +
      Marital_Status +
      as.factor(household_size) + 
      #as.factor(Household_Composition) +
      month + 
      year,
      # (1|quarter) +
      # (1 + income_demo_ranger_sar_scale|fip_code) +
      # (1 + income_scale | fips_code),
    data = 
      qh_calories_imputed_sc_by_household_monthly  %>% filter(year <= 2016)
  )

summary(lm1)
regclass::VIF(lm1)
lm.beta::lm.beta(lm1)

tidy_lm1 <- tidy(lm1)
```

```{r}
est <- 
  tidy_lm1 %>% 
  dplyr::filter(term == "med_inc_niel_avg_scale") %>% 
  dplyr::select(estimate)

tidy_lm1 <-
  tidy_lm1 %>% 
  mutate(
    dot_color = ifelse(estimate < 0, "red1", ifelse(estimate > 0, "dodgerblue2", NA)),
    se = std.error
  )

tidy_lm1 <-
  tidy_lm1 %>% 
  filter(
    term == "med_inc_niel_avg_scale" |
    term == "income_scale" |
    term == "Male_Head_Education_scale" | 
    term == "Female_Head_Education_scale" 
  ) %>% 
  mutate(
    variable = 
      case_when(
        term == "med_inc_niel_avg_scale" ~ "demographic reference \n median income",
        term == "income_scale" ~ "household income",
        term == "Male_Head_Education_scale" ~ "male head education",
        term == "Female_Head_Education_scale" ~ "female head education"
      )
  ) 

col <- as.character(tidy_lm1$dot_color)
names(col) <- as.character(tidy_lm1$dot_color)

grocery_spend_demog <-
  tidy_lm1 %>% 
  ggplot(aes(reorder(as.factor(variable), estimate), estimate)) +
  geom_point(aes(color = dot_color), size = 4) +
  geom_errorbar(aes(ymin = estimate - 2 * se, ymax = estimate + 2 * se), width = 0) + 
  scale_color_manual(values = col) +
  geom_hline(yintercept = -abs(est$estimate), linetype = "dashed", color = "red") +
  geom_hline(yintercept = 0, linetype = "dashed") +
  geom_hline(yintercept = abs(est$estimate), linetype = "dashed", color = "red") +
  scale_y_continuous(
    breaks = c( -0.3, -0.2, -0.1, 0, 0.1, 0.2, 0.3),
    limits = c(-0.35, 0.35)
  ) +
  labs(
    y = "standardized beta",
    x = "variable"
  ) +
  theme_bw() +
  theme(
    text = element_text(size = 17),
    plot.title = element_text(hjust = 0.5),
    legend.position = "none"
  ) +
  coord_flip()

grocery_spend_demog

ggsave(
  "G:/My Drive/research/projects/niel/nielsen_analysis/relative_status_analysis/plots/grocery_spend_demog.png",
  grocery_spend_demog,
  width = 8,
  height = 6,
  dpi = 500
)
```
```{r}
lm2 <-
  lm(
    yes_scale ~
      median_income_county_scale +
      income_scale +
      Male_Head_Education_scale +
      Female_Head_Education_scale +
      Male_Head_Age_scale +
      Female_Head_Age_scale +
      Male_Head_Employment +
      Female_Head_Employment +
      median_monthly_housing_cost_county_scale +
      land_area_2010_scale +
      total_pop_county_scale +
      Race +
      Male_Head_Employment +
      Female_Head_Employment +
      Marital_Status +
      Household_Size_scale + 
      quarter + 
      year,
    data = nielsen_dollar_budget %>% filter(!is.na(median_income_county_scale))
  )

summary(lm2)

tidy_lm2 <- tidy(lm2)
```

```{r}
est <- 
  tidy_lm2 %>% 
  dplyr::filter(term == "median_income_county_scale") %>% 
  dplyr::select(estimate)

tidy_lm2 <-
  tidy_lm2 %>% 
  mutate(
    dot_color = ifelse(estimate < 0, "red1", ifelse(estimate > 0, "dodgerblue2", NA)),
    se = std.error
  )

tidy_lm2 <-
  tidy_lm2 %>% 
  filter(
    term == "median_income_county_scale" |
    term == "income_scale" |
    term == "Male_Head_Education_scale" | 
    term == "Female_Head_Education_scale" 
  ) %>% 
  mutate(
    variable = 
      case_when(
        term == "median_income_county_scale" ~ "geographic reference \n median income",
        term == "income_scale" ~ "household income",
        term == "Male_Head_Education_scale" ~ "male head education",
        term == "Female_Head_Education_scale" ~ "female head education"
      )
  ) 

col <- as.character(tidy_lm2$dot_color)
names(col) <- as.character(tidy_lm2$dot_color)

grocery_spend_geog <-
  tidy_lm2 %>% 
  ggplot(aes(reorder(as.factor(variable), estimate), estimate)) +
  geom_point(aes(color = dot_color), size = 4) +
  geom_errorbar(aes(ymin = estimate - 2 * se, ymax = estimate + 2 * se), width = 0) + 
  scale_color_manual(values = col) +
  geom_hline(yintercept = -abs(est$estimate), linetype = "dashed", color = "red") +
  geom_hline(yintercept = 0, linetype = "dashed") +
  geom_hline(yintercept = abs(est$estimate), linetype = "dashed", color = "red") +
  scale_y_continuous(
    breaks = c( -0.3, -0.2, -0.1, 0, 0.1, 0.2, 0.3),
    limits = c(-0.35, 0.35)
  ) +
  labs(
    y = "standardized beta",
    x = "variable"
  ) +
  theme_bw() +
  theme(
    text = element_text(size = 17),
    plot.title = element_text(hjust = 0.5),
    legend.position = "none"
  ) +
  coord_flip()

grocery_spend_geog

ggsave(
  "G:/My Drive/research/projects/niel/nielsen_analysis/relative_status_analysis/plots/grocery_spend_geog.png",
  grocery_spend_geog,
  width = 8,
  height = 6,
  dpi = 500
)
```




```{r}
lm1 <-
  lm(
    yes_scale ~
      med_inc_niel_avg_scale +
      income_scale +
      Male_Head_Education_scale +
      Female_Head_Education_scale +
      Male_Head_Age_scale +
      Female_Head_Age_scale +
      Male_Head_Employment +
      Female_Head_Employment +
      median_monthly_housing_cost_county_scale +
      land_area_2010_scale +
      total_pop_county_scale +
      Race +
      Male_Head_Employment +
      Female_Head_Employment +
      Marital_Status +
      Household_Size_scale + 
      quarter + 
      year,
    data = nielsen_calorie_budget %>% filter(!is.na(med_inc_niel_avg_scale))
  )

summary(lm1)

tidy_lm1 <- tidy(lm1)
```

```{r}
est <- 
  tidy_lm1 %>% 
  dplyr::filter(term == "med_inc_niel_avg_scale") %>% 
  dplyr::select(estimate)

tidy_lm1 <-
  tidy_lm1 %>% 
  mutate(
    dot_color = ifelse(estimate < 0, "red1", ifelse(estimate > 0, "dodgerblue2", NA)),
    se = std.error
  )

tidy_lm1 <-
  tidy_lm1 %>% 
  filter(
    term == "med_inc_niel_avg_scale" |
    term == "income_scale" |
    term == "Male_Head_Education_scale" | 
    term == "Female_Head_Education_scale" 
  ) %>% 
  mutate(
    variable = 
      case_when(
        term == "med_inc_niel_avg_scale" ~ "demographic reference \n median income",
        term == "income_scale" ~ "household income",
        term == "Male_Head_Education_scale" ~ "male head education",
        term == "Female_Head_Education_scale" ~ "female head education"
      )
  ) 

col <- as.character(tidy_lm1$dot_color)
names(col) <- as.character(tidy_lm1$dot_color)

calorie_budget_demog <-
  tidy_lm1 %>% 
  ggplot(aes(reorder(as.factor(variable), estimate), estimate)) +
  geom_point(aes(color = dot_color), size = 4) +
  geom_errorbar(aes(ymin = estimate - 2 * se, ymax = estimate + 2 * se), width = 0) + 
  scale_color_manual(values = col) +
  geom_hline(yintercept = -abs(est$estimate), linetype = "dashed", color = "red") +
  geom_hline(yintercept = 0, linetype = "dashed") +
  geom_hline(yintercept = abs(est$estimate), linetype = "dashed", color = "red") +
  scale_y_continuous(
    breaks = c( -0.3, -0.2, -0.1, 0, 0.1, 0.2, 0.3),
    limits = c(-0.25, 0.25)
  ) +
  labs(
    y = "standardized beta",
    x = "variable"
  ) +
  theme_bw() +
  theme(
    text = element_text(size = 17),
    plot.title = element_text(hjust = 0.5),
    legend.position = "none"
  ) +
  coord_flip()

calorie_budget_demog

ggsave(
  "G:/My Drive/research/projects/niel/nielsen_analysis/relative_status_analysis/plots/calorie_budget_demog.png",
  calorie_budget_demog,
  width = 8,
  height = 6,
  dpi = 500
)
```
```{r}
lm2 <-
  lm(
    yes_scale ~
      median_income_county_scale +
      income_scale +
      Male_Head_Education_scale +
      Female_Head_Education_scale +
      Male_Head_Age_scale +
      Female_Head_Age_scale +
      Male_Head_Employment +
      Female_Head_Employment +
      median_monthly_housing_cost_county_scale +
      land_area_2010_scale +
      total_pop_county_scale +
      Race +
      Male_Head_Employment +
      Female_Head_Employment +
      Marital_Status +
      Household_Size_scale + 
      quarter + 
      year,
    data = nielsen_calorie_budget %>% filter(!is.na(median_income_county_scale))
  )

summary(lm2)

tidy_lm2 <- tidy(lm2)
```

```{r}
est <- 
  tidy_lm2 %>% 
  dplyr::filter(term == "median_income_county_scale") %>% 
  dplyr::select(estimate)

tidy_lm2 <-
  tidy_lm2 %>% 
  mutate(
    dot_color = ifelse(estimate < 0, "red1", ifelse(estimate > 0, "dodgerblue2", NA)),
    se = std.error
  )

tidy_lm2 <-
  tidy_lm2 %>% 
  filter(
    term == "median_income_county_scale" |
    term == "income_scale" |
    term == "Male_Head_Education_scale" | 
    term == "Female_Head_Education_scale" 
  ) %>% 
  mutate(
    variable = 
      case_when(
        term == "median_income_county_scale" ~ "geographic reference \n median income",
        term == "income_scale" ~ "household income",
        term == "Male_Head_Education_scale" ~ "male head education",
        term == "Female_Head_Education_scale" ~ "female head education"
      )
  ) 

col <- as.character(tidy_lm2$dot_color)
names(col) <- as.character(tidy_lm2$dot_color)

calorie_budget_geog <-
  tidy_lm2 %>% 
  ggplot(aes(reorder(as.factor(variable), estimate), estimate)) +
  geom_point(aes(color = dot_color), size = 4) +
  geom_errorbar(aes(ymin = estimate - 2 * se, ymax = estimate + 2 * se), width = 0) + 
  scale_color_manual(values = col) +
  geom_hline(yintercept = -abs(est$estimate), linetype = "dashed", color = "red") +
  geom_hline(yintercept = 0, linetype = "dashed") +
  geom_hline(yintercept = abs(est$estimate), linetype = "dashed", color = "red") +
  scale_y_continuous(
    breaks = c( -0.3, -0.2, -0.1, 0, 0.1, 0.2, 0.3),
    limits = c(-0.25, 0.25)
  ) +
  labs(
    y = "standardized beta",
    x = "variable"
  ) +
  theme_bw() +
  theme(
    text = element_text(size = 17),
    plot.title = element_text(hjust = 0.5),
    legend.position = "none"
  ) +
  coord_flip()

calorie_budget_geog

ggsave(
  "G:/My Drive/research/projects/niel/nielsen_analysis/relative_status_analysis/plots/calorie_budget_geog.png",
  calorie_budget_geog,
  width = 8,
  height = 6,
  dpi = 500
)
```